spring.application.name=Sales Analyst

spring.datasource.url=jdbc:postgresql://localhost:5432/SalesDatabase
spring.datasource.username=postgres
spring.datasource.password=251204

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Config swagger
#path: http://localhost:8080/swagger-ui/index.html
open.api.title=API service document
open.api.version=1.0.0
open.api.description=Sale Analyst - Swagger Docs

#Config token
jwt.expiration-refresh-token=5184000
jwt.secretKey=your_jwt_secret
jwt.expiration=2592000

api.prefix=/api/v1

#Cloudinary
cloudinary.cloud_name=your_cloud_name
cloudinary.api_key=your_api_key
cloudinary.api_secret=your_api_secret

#size upload
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
