spring.application.name=Sales Analyst

spring.datasource.url=jdbc:postgresql://localhost:5432/SalesDatabase
spring.datasource.username=postgres
spring.datasource.password=0848001595

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Config swagger
#path: http://localhost:8080/swagger-ui/index.html
#open.api.title=API service document
#open.api.version=1.0.0
#open.api.description=API for Speed tracking system